import matplotlib.pyplot as plt
import numpy as np
from gtsam import Marginals as Marginals, Point2 as Point2, Point3 as Point3, Pose2 as Pose2, Pose3 as Pose3, Values as Values
from mpl_toolkits.mplot3d import Axes3D as Axes3D
from typing import Iterable

def set_axes_equal(fignum: int) -> None: ...
def ellipsoid(rx: float, ry: float, rz: float, n: int) -> tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def plot_covariance_ellipse_3d(axes, origin: Point3, P: np.ndarray, scale: float = 1, n: int = 8, alpha: float = 0.5) -> None: ...
def plot_covariance_ellipse_2d(axes, origin: Point2, covariance: np.ndarray) -> None: ...
def plot_point2_on_axes(axes, point: Point2, linespec: str, P: np.ndarray | None = None) -> None: ...
def plot_point2(fignum: int, point: Point2, linespec: str, P: np.ndarray = None, axis_labels: Iterable[str] = ('X axis', 'Y axis')) -> plt.Figure: ...
def plot_pose2_on_axes(axes, pose: Pose2, axis_length: float = 0.1, covariance: np.ndarray = None) -> None: ...
def plot_pose2(fignum: int, pose: Pose2, axis_length: float = 0.1, covariance: np.ndarray = None, axis_labels=('X axis', 'Y axis', 'Z axis')) -> plt.Figure: ...
def plot_point3_on_axes(axes, point: Point3, linespec: str, P: np.ndarray | None = None) -> None: ...
def plot_point3(fignum: int, point: Point3, linespec: str, P: np.ndarray = None, axis_labels: Iterable[str] = ('X axis', 'Y axis', 'Z axis')) -> plt.Figure: ...
def plot_3d_points(fignum, values, linespec: str = 'g*', marginals=None, title: str = '3D Points', axis_labels=('X axis', 'Y axis', 'Z axis')) -> None: ...
def plot_pose3_on_axes(axes, pose, axis_length: float = 0.1, P=None, scale: int = 1) -> None: ...
def plot_pose3(fignum: int, pose: Pose3, axis_length: float = 0.1, P: np.ndarray = None, axis_labels: Iterable[str] = ('X axis', 'Y axis', 'Z axis')) -> plt.Figure: ...
def plot_trajectory(fignum: int, values: Values, scale: float = 1, marginals: Marginals = None, title: str = 'Plot Trajectory', axis_labels: Iterable[str] = ('X axis', 'Y axis', 'Z axis')) -> None: ...
def plot_incremental_trajectory(fignum: int, values: Values, start: int = 0, scale: float = 1, marginals: Marginals | None = None, time_interval: float = 0.0) -> None: ...
