import gtsam
import numpy as np
from _typeshed import Incomplete

I: Incomplete

def simulate_car() -> list[float]: ...
def error_gps(measurement: np.ndarray, this: gtsam.CustomFactor, values: gtsam.Values, jacobians: list[np.ndarray] | None) -> float: ...
def error_odom(measurement: np.ndarray, this: gtsam.CustomFactor, values: gtsam.Values, jacobians: list[np.ndarray] | None) -> float: ...
def error_lm(measurement: np.ndarray, this: gtsam.CustomFactor, values: gtsam.Values, jacobians: list[np.ndarray] | None) -> float: ...
def main() -> None: ...
