from _typeshed import Incomplete
from gtsam import BetweenFactorConstantBias as BetweenFactorConstantBias, Cal3_S2 as Cal3_S2, ConstantTwistScenario as ConstantTwistScenario, ISAM2 as ISAM2, ImuFactor as ImuFactor, NonlinearFactorGraph as NonlinearFactorGraph, PinholeCameraCal3_S2 as PinholeCameraCal3_S2, Point3 as Point3, Pose3 as Pose3, PriorFactorConstantBias as PriorFactorConstantBias, PriorFactorPose3 as PriorFactorPose3, PriorFactorVector as PriorFactorVector, Rot3 as Rot3, Values as Values
from gtsam.symbol_shorthand import B as B, V as V, X as X
from gtsam.utils import plot as plot
from mpl_toolkits.mplot3d import Axes3D as Axes3D

def vector3(x, y, z): ...

g: float
n_gravity: Incomplete

def preintegration_parameters(): ...
def get_camera(radius): ...
def get_scenario(radius, pose_0, angular_velocity, delta_t): ...
def IMU_example() -> None: ...
