from _typeshed import Incomplete
from gtsam import Pose2 as Pose2
from gtsam.utils.test_case import GtsamTestCase as GtsamTestCase
from mpl_toolkits.mplot3d import Axes3D as Axes3D

def vector3(x, y, z): ...
def compose(*poses): ...
def vee(M): ...
def delta(g0, g1): ...
def trajectory(g0, g1, N: int = 20): ...

class ThreeLinkArm:
    L1: float
    L2: float
    L3: float
    xi1: Incomplete
    xi2: Incomplete
    xi3: Incomplete
    sXt0: Incomplete
    def __init__(self) -> None: ...
    def fk(self, q): ...
    def jacobian(self, q): ...
    def poe(self, q): ...
    def con(self, q): ...
    def ik(self, sTt_desired, e: float = 1e-09): ...
    def manipulator_jacobian(self, q): ...
    def plot(self, fignum, q): ...

Q0: Incomplete
Q1: Incomplete
Q2: Incomplete

class TestPose2SLAMExample(GtsamTestCase):
    arm: Incomplete
    def setUp(self) -> None: ...
    def assertPose2Equals(self, actual, expected, tol: float = 0.01) -> None: ...
    def test_fk_arm(self) -> None: ...
    def test_jacobian(self) -> None: ...
    def test_con_arm(self) -> None: ...
    def test_poe_arm(self) -> None: ...
    def test_ik(self) -> None: ...
    def test_manipulator_jacobian(self) -> None: ...

def run_example() -> None: ...
