import gtsam

def report_on_progress(graph: gtsam.NonlinearFactorGraph, current_estimate: gtsam.Values, key: int): ...
def create_poses() -> list[gtsam.Pose3]: ...
def determine_loop_closure(odom_tf: gtsam.Pose3, current_estimate: gtsam.Values, key: int, xyz_tol: float = 0.6, rot_tol: int = 17) -> int: ...
def Pose3_ISAM2_example() -> None: ...
