import gtsam
import numpy as np

def report_on_progress(graph: gtsam.NonlinearFactorGraph, current_estimate: gtsam.Values, key: int): ...
def determine_loop_closure(odom: np.ndarray, current_estimate: gtsam.Values, key: int, xy_tol: float = 0.6, theta_tol: int = 17) -> int: ...
def Pose2SLAM_ISAM2_example() -> None: ...
